### ISSUE TITLE
Pytest version conflict at installing project dependencies

### ISSUE THREAD

**Issue by jjpaulo2** [pygame/pygameweb#106]
The following command generates an error caused by `pytest==3.4.0` pinned on `requeriments.dev.txt`.
 
`$ pip install -r requirements.dev.txt --use-feature=2020-resolver`

> ERROR: Cannot install pytest==3.4.0, pytest-cache 1.0, pytest-cov 2.5.1 and pytest-flask 0.15.0 because these package versions have conflicting dependencies.
>
> The conflict is caused by:
>     The user requested pytest==3.4.0
>     pytest-cache 1.0 depends on pytest>=2.2
>     pytest-cov 2.5.1 depends on pytest>=2.6.0
>     pytest-flask 0.15.0 depends on pytest>=3.6
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

Just removing the `pytest` version from `requirements.dev.txt` for getting the latest version may solve the problem, as done on `.travis.yml` that runs `pip install --upgrade pytest`.

**Comment by thiagojobson** [comment]
Thanks for reporting this.

Related to #95.

**Comment by jjpaulo2** [comment]
I did a pull request that fix this specific pytest problem. Please, check it.
