### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by Salvakiya** [pygame/pygameweb#108]
seems you cant register a new user on pygame.org

**Comment by christianbitter** [comment]
> Same problem for me since ages.

**Comment by rkunkel-student** [comment]
Same Issue here. It keeps displaying "Registration Disabled" - Was this functionality removed?

**Comment by Jihene-ch** [comment]
A month later, this is still an issue. It shows "Registration disabled" at the level of the email address. But why does it also show "If your email account already exists, you may need to Confirm your account first."
I don't think this functionality was simply removed.

**Comment by remram44** [comment]
The resources page has a lot of dead links: https://www.pygame.org/wiki/resources?parent=index

Tried to do something about it but I can't register. Is this website maintained?

**Comment by leha-code** [comment]
It isnt

**Comment by shinysocks** [comment]
also cannot register and yet I continue to see new projects.

**Comment by elliottower** [comment]
Two years later and I also can't register, would like to add new projects. I sent an email to the contact (majordomo@seul.org) but I suspect that may not be up to date
