### ISSUE TITLE
Higher Resolution Pygame Logos

### ISSUE THREAD

**Issue by Just-JC** [pygame/pygameweb#109]
Not sure this is the right place to post this, but I recently managed to trace all pygame logos into SVG's. In many places where the official logos are used, the images are either poorly upscaled or blurry, or with artifacts and jagged edges.

I thought this new one might be useful for the pygame organization to be used on the website among other places.

Any feedback is welcome.

**All Files:**
https://drive.google.com/drive/folders/14iWMTgC9tI2TiE93-eBVYxYYrXSeldTs?usp=sharing

![Pygame Logo Trace Type 1](https://user-images.githubusercontent.com/65417594/104594821-fe240a00-5671-11eb-9a95-67652a4bab26.png)

**Comment by Jihene-ch** [comment]
Could you perhaps do the same to the logo used in the README.rst in the original library repository ?  Or maybe we could replace it with this one ?

**Comment by Just-JC** [comment]
I also did it for other versions of the pygame logo (pygame in green letters, pygame powered), click on the google drive link to see those.

**Comment by Just-JC** [comment]
I moved this to the main pygame repository, so I'll close this, see here: https://github.com/pygame/pygame/issues/2701
