### ISSUE TITLE
Annoying book banner in docs

### ISSUE THREAD

**Issue by Matiiss** [pygame/pygameweb#120]
Not a major issue but the _pygame 4000 book update_ banner in the documentation is quite annoying and it has been there for quite a while. While you are at the top of the page it doesn't bother much, because all of the hyperlinks are easily accessible, however, when you go to a specific method for some object, the banner covers the method name and some of the argument information when you "jump" to it or when accessing the specific URL for that method (e.g. [`pygame.Surface.blit`](https://www.pygame.org/docs/ref/surface.html#pygame.Surface.blit), you should quite clearly see that the method name and partially the arguments are covered by the rather large banner). It is not something too crazy and it is not too hard to scroll a bit up, but it is still annoying.

My suggestion is that it is left at the top of the docs (above the little menu where you can choose which part of the docs you want to see (_the most useful stuff_, _more advanced stuff_, ...)) or maybe it can be closable (with a little "x" on the side) or it fades away, or it is put on the side or perhaps even the bottom. Just to make it less annoying.

**Comment by pdtangney** [comment]
Why is this closed as complete. The banner is still there.
