### ISSUE TITLE
domain expiration

### ISSUE THREAD

**Issue by PeterShinners** [pygame/pygameweb#121]
The pygame.org domain is up for renewal. I'm happy to pay for another chunk of years. Are there better options for registrars in 2022? If I don't hear anything soon I'll make to payment to prevent things from expiring.

**Comment by hashimamas** [comment]
The registration has been renewed for another 4 years. See you then.

**Comment by PeterShinners** [comment]
Domain registration has been renewed for another four years. See you all then.

**Comment by koutoftimer** [comment]
@PeterShinners can you take a look at #131 ?
