### ISSUE TITLE
Website Down or something

### ISSUE THREAD

**Issue by narf99** [pygame/pygameweb#123]
![error](https://user-images.githubusercontent.com/53348921/156050643-4e56bb8c-c99e-41b2-871a-4a1147277c2a.PNG)
I get this error whenever I try and access the website. Does anybody else get this error or is it just me?

**Comment by YariKartoshe4ka** [comment]
the same

**Comment by towe96** [comment]
The message is all good and well, but completely breaking the documentation for a library for political reasons is just evil. A banner would've sufficed.

**Comment by DavidBuchanan314** [comment]
I'm getting a similar error.

Looking into the page source, it's actually a Cloudflare access denied error page:

```html
  <h1>Access denied</h1>
  <p>You do not have access to www.pygame.org.</p><p>The site owner may have set restrictions that prevent you from accessing the site.</p>
  ```
  
 I can visit the site just fine from other IP addresses, but not from my home IP - it appears that I've been banned somehow, which is weird. Who can I contact about getting this lifted?

**Comment by DavidBuchanan314** [comment]
I see this issue is closed as completed. This is what I currently get, trying to visit https://www.pygame.org/docs/ref/pygame.html:

```html
<html>
<head>
   <meta charset="UTF-8">

</head>
<body>
The pygame website is going down for a little nap.

<br><br>
NO LOUD NOISES... please :)

<br><br> <br><br> <br><br> <br><br>
<br><br> <br><br> <br><br> <br><br>
<hr>
<small>

    ::ALWAYS_ONLINE_NO_COPY_BOX::

    ::CLOUDFLARE_ERROR_500S_BOX::

    ::CLOUDFLARE_ERROR_1000S_BOX::

</small>
</body>
</html>
```

**Comment by Darquesse27** [comment]
I’ve been getting exactly the same “No loud noises” error as @DavidBuchanan314 did last year for the last 24 hours or so whenever I try and access the front page of the website (pygame.org/news). This time though it seems like it’s happening across all my devices, on my home wifi and on cellular, both with and without my VPN active, which is a bit odd! The other odd thing is that I can still access the documentation pages and dashboard on all devices/networks just fine - it’s just the rest of the website that’s down!

**Comment by 0dminnimda** [comment]
Getting the same error as @DavidBuchanan314 What's the point of braking the docs page of an open source project? I'd assume @illume can answer this question.

**Comment by DavidBuchanan314** [comment]
By the way, I don't have the issue anymore, on my end at least
