### ISSUE TITLE
one of the links in the Resources page leads to a pornographic website

### ISSUE THREAD

**Issue by aaarbk** [pygame/pygameweb#124]
Specifically, in the tutorials section of [this page](https://www.pygame.org/wiki/resources), there is a link that reads [spriteart.com Pixel art tutorials.](http://www.spriteart.com/) which turned out to be a pornographic website. Please remove the link.

**Comment by thiagojobson** [comment]
Thanks, I just removed it 👍

**Comment by aaarbk** [comment]
Thanks for resolving this quickly!
