### ISSUE TITLE
pygame.org got a HTTP 500 Internal Server Error

### ISSUE THREAD

**Issue by lulunac27a** [pygame/pygameweb#131]
When I go to pygame.org, I got a HTTP 500 error message and the website is not working right now

**Comment by Untitled-user1** [comment]
Me too, and I can't install pygame by Powershell

**Comment by mistamun** [comment]
Still down

**Comment by PeterShinners** [comment]
Getting a server error like 500 implies the dns and nameservers are all working. I don't have info on what the http server itself is running three days.

**Comment by Untitled-user1** [comment]
Still down, but somehow the documentation page still works. https://www.pygame.org/docs/

**Comment by Untitled-user1** [comment]
Also it can load favicon.ico on the error page, but it seems like it's not the same one as the one on the docs page.
