### ISSUE TITLE
Create users locally without email confirmation?

### ISSUE THREAD

**Issue by takluyver** [pygame/pygameweb#14]
Setting up an outgoing email server is a pain. It would be nice to have a way to create users for debugging while bypassing the email confirmation.

Workaround: run with `APP_DEBUG=1`, get the traceback when it fails to send a confirmation, and use the interactive debugger to get the confirmation link. Copy and paste the link to the URL bar and ta-da, confirmed.

**Comment by takluyver** [comment]
One simple way to work around this would be to have a script that populates the database with a few pre-confirmed testing users (e.g. one admin, a couple of regular users, and a blocked user) with obvious usernames and passwords for testing with.

**Comment by illume** [comment]
Yeah, having a few testing users set up would be nice.

There is some documentation on Flask-Mail for suppressing email sending, and logging emails:
https://pythonhosted.org/Flask-Mail/#signalling-support

Maybe APP_DEBUG could print emails out by default on the console? Testing with a gmail account works for me.

**Comment by poikilos** [comment]
for now you can do it manually:
* first get the id
```
sudo -u postgres psql pygame -c "SELECT * FROM groups;"
echo '* pygameweb groups should appear above'
sudo -u postgres psql pygame -c "SELECT * FROM users;"
```
* after you get the id of the user you want above, and group, set the admin_id and group_id variables in the script below: 
```
admin_id=1
mod_group_id=12
sudo -u postgres psql pygame -c "INSERT into users_groups values ($admin_id, $mod_group_id)"
sudo -u postgres psql pygame -c "UPDATE users set active=True where id=$admin_id"
sudo -u postgres psql pygame -c "UPDATE users set confirmed_at='2018-08-08 16:07:43.657477-04' where id=$admin_id"
```
* now the user should be able to log in. Also, the following should show the data above was entered:
```
sudo -u postgres psql pygame -c "SELECT active,name,confirmed_at,disabled,super,registered_at FROM users where id=$admin_id"
sudo -u postgres psql pygame -c "SELECT * FROM users_groups;"
```
