### ISSUE TITLE
Unable to delete a release

### ISSUE THREAD

**Issue by viblo** [pygame/pygameweb#15]
It seems like the delete release feature doesnt work.

I have a project listed on the pygame web page here: http://www.pygame.org/project/780 In the beginning I added all releases there as well, but now I dont want to have them there anymore. I tried deleting them, but I only get a error message that says: "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.". The same happens on every release I tired to remove.

**Comment by illume** [comment]
The "delete release" function works now.

**Comment by viblo** [comment]
Thanks, seems to work now.
