### ISSUE TITLE
404 on admin site

### ISSUE THREAD

**Issue by takluyver** [pygame/pygameweb#16]
@illume I just went to check the admin site, but all the URLs I've used before now give me 404. Did my changes in #13 break something?

**Comment by takluyver** [comment]
ping @illume - there is now spam again on the site, but I can't get on to the admin pages to do anything about it.

**Comment by illume** [comment]
That flask admin based thing isn't coming back I'm afraid. It exposes too much info. Instead admin tools will be added for tasks as needed.

When logged in as admin there's a [Spam] and [Delete] button on the project comments link. Some people have been using that to mark things as spam. Spam marking buttons on the projects page coming up.

**Comment by takluyver** [comment]
OK, fair enough.

Is there also going to be a way for an admin to edit tags? E.g. the author of [this project](http://www.pygame.org/project/3359/5425) probably meant to add five short tags to it, rather than one five-word tag.

**Comment by illume** [comment]
Hrmm. I guess it would be useful for admins to edit project entries sometimes. Another case is fixing old urls.
