### ISSUE TITLE
Run with sqlite for development

### ISSUE THREAD

**Issue by takluyver** [pygame/pygameweb#17]
The need to set up postgres makes it harder to get started with developing the site. It's already using SQLAlchemy as an abstraction layer over the database. Would it be practical to configure it to run with SQLite in development, so that there's a lower barrier to contribution?

**Comment by illume** [comment]
I like the goal of making it easier to make changes, and it was a goal to try and keep it DB independent.

Main issue with using SQLite and this is that there's some PostgreSQL features used in the test suite for running database queries inside transactions for speed. These could probably be factored out to just not do that for SQLite. Maybe some of the tests would need to be fixed to clean up manually. There's probably other issues in there with field handling, and maybe some of the joins need to be fixed. There's a page or so of bare SQL that still needs translating to sqlalchemy. That's the issues from my memory.

I'll work towards making it more DB independent in the future, but it's not work I want to focus on now. PRs accepted... yada yada.
