### ISSUE TITLE
The link to "Thepythongamebook tutorial about Pygame" in tutorials page is not found

### ISSUE THREAD

**Issue by douglasdcm** [pygame/pygameweb#174]
Hi, how are you? I have been following the tutorials in [Tutorials page](https://www.pygame.org/wiki/tutorials) and I noticed that the link to "Thepythongamebook tutorial about Pygame" is not working.

I removed the "/en:pygame:start" part and I was redirected to a valid page, but I'm not sure it is the correct link: https://thepythongamebook.com/#

**Evidences:**

**Main page**
![image](https://github.com/pygame/pygameweb/assets/29078346/98706c20-28b7-4236-a8ce-067cf110f7b6)

**Thepythongamebook tutorial about Pygame**
![image](https://github.com/pygame/pygameweb/assets/29078346/95e14861-1972-4ca0-a606-cb1b0b19af61)

**Comment by illume** [comment]
Thanks, I cleaned up some broken/old links on there.
