### ISSUE TITLE
PyGames

### ISSUE THREAD

**Issue by PR4BIR** [pygame/pygameweb#178]
500
THE SERVER ENCOUNTERED AN INTERNAL ERROR AND WAS UNABLE TO COMPLETE YOUR REQUEST.
EITHER THE SERVER IS OVERLOADED OR THERE IS AN ERROR IN THE APPLICATION.

**Comment by MisterKirill** [comment]
![image](https://github.com/pygame/pygameweb/assets/87936030/36d30583-aecc-4e21-b3f5-8ace307b4a7e)

**Comment by kornerr** [comment]
::WHAT_A_SHAME::

**Comment by kornerr** [comment]
The site is still down
