### ISSUE TITLE
HTTP should redirect to HTTPS

### ISSUE THREAD

**Issue by bittner** [pygame/pygameweb#18]
Currently, when you enter [pygame.org](http://pygame.org) and try to log in with your account a sensible web browser will warn you that the connection is insecure and your credentials can be sniffed out from your connection by an attacker.

The typical solution to this problem is to:

- either use HTTPS for the website in general (i.e. redirect HTTP to HTTPS in general),
- or redirect to HTTPS on the login page (and any other page that handles login information)

Suggested Solution
--------------------------
I can't find any deployment configuration in the repository, that makes it a bit hard to suggest changes or provide a patch. The following code samples may work for Nginx:

```nginx
server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name _;
  return 301 https://$host$request_uri;
}
```
or
```nginx
if ($host ~* ^(example\.com|www\.example\.com)$ ){
  rewrite  ^/(.*)$  https://example.com/$1  permanent;
}
```
Sources: [bjornjohansen.no](https://bjornjohansen.no/redirect-to-https-with-nginx), [nixCraft](https://www.cyberciti.biz/faq/linux-unix-nginx-redirect-all-http-to-https/)

**Comment by illume** [comment]
Thanks. The reasoning follows why this was chosen to work as it does.

We require that the website be usable over normal HTTP, because some users are blocked from HTTPS. A user can choose already to use HTTPS (which technically still does have a MITM attacks going on from university/corp/country proxies and the like). They get a warning doing so. We could also use HSTS (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security) which is the proper solution rather than redirects, but that means HTTP doesn't work.

It will stay as it is for the moment.

**Comment by takluyver** [comment]
Who's blocked from using HTTPS? Are we sure that's still a thing in 2017? I
think much of the modern web would be unusable if you blocked HTTPS.

**Comment by bittner** [comment]
True, 10 years ago this might have been a thing. Locations that block HTTPS (and allow unsecure HTTP) should probably order an upgrade to their service level agreement.

**Comment by illume** [comment]
Hello,

Thanks for the suggestion, and for submitting the issue.

pygame.org urls permanently redirect to https://www.pygame.org/ now, and the login urls even on non-https point to https. Additionally, I've updated lots of links in the docs and on the internet to https urls, and will continue doing that where possible. 

Browsers are now rolling out https upgrade headers, where they go to a https url when one is available. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests
Seems to be at 77%, and even the latest version of Edge supports it. https://caniuse.com/#feat=upgradeinsecurerequests

Search engines always link to https (if available) it seems, and adding canonical https link tags in the headers is being tracked here: https://github.com/pygame/pygameweb/issues/34

With these changes(not including upgrade-insecure-requests, which I just enabled today), there's been a 36% increase in https connections, and now the majority of connections are using https. Hopefully as more links are updated (18 years of links on the interwebs might not ever be upgraded).

Cloudflare (which pygame.org is using for https) supports https a long way back (we are using the pro plan). Even my android 2 phone works with it. https://support.cloudflare.com/hc/en-us/articles/203041594-What-browsers-work-with-Cloudflare-s-SSL-certificates-

www.pygame.org is still open for business on http however, even though most people probably won't go there soon. The people in far off places with weird internet connections, and those retro computing people on "AmigaVoyager/3.2 (AmigaOS/MC680x0)" will still be able to download their files.
