### ISSUE TITLE
No 'Previous' link on page 2 of Projects page

### ISSUE THREAD

**Issue by ThomasMNS** [pygame/pygameweb#3]
Hi all, 

Love the new site. There seems to be a tiny issue with the pagination on the projects page, where when navigating between pages of projects there is no 'previous' link on page 2, with it not appearing until page 3. 

Kindest regards, 
Tom

**Comment by takluyver** [comment]
Looks like `prev_start` is set to 0 [here](https://github.com/pygame/pygameweb/blob/master/pygameweb/project/views.py#L146), and then it doesn't count as true [in the template](https://github.com/pygame/pygameweb/blob/4d1c5153de1f8133907c23f5926b8229afdd1859/pygameweb/templates/project/tags.html#L40). Do you want to whip up a PR?

**Comment by illume** [comment]
Thanks! :)
