### ISSUE TITLE
Migration errors and Foreign key constraint errors during code setup

### ISSUE THREAD

**Issue by abhiramr** [pygame/pygameweb#38]
In addition to " public_tags_project_id0_idx" migration mentioned in #10 , the other migration that threw an error was "public_tags_value1_idx". 
Also, a foreign key constraint error was thrown - 
```
    cursor.execute(statement, parameters)
psycopg2.IntegrityError: insert or update on table "users_groups" violates foreign key constraint "users_groups_users_id_fkey"
DETAIL:  Key (users_id)=(95) is not present in table "users".


```
I commented out the corresponding migration create and drop references and foreign key constraints to proceed with the " alembic upgrade head" operation. 

It executed fine after that, but these workarounds had to be carried out. What problems will this cause?

**Comment by thiagojobson** [comment]
@illume you can close this as well.
