### ISSUE TITLE
"Pygame FAQ" navbar item incorrect URL when on wiki pages

### ISSUE THREAD

**Issue by ThomasMNS** [pygame/pygameweb#4]
When on a wiki page, such as "About", the "Pygame FAQ" navbar item incorrectly links to http://pygame.org/wiki/wiki/FrequentlyAskedQuestions, rather than http://pygame.org/wiki/FrequentlyAskedQuestions

When viewing a none wiki page, such as "News", "Projects" or "What's New", the correct link is used. 

Kindest regards, 
Tom

**Comment by illume** [comment]
Thanks again.
