### ISSUE TITLE
https://www.pygame.org/docs/ fails to call https://nullege.com

### ISSUE THREAD

**Issue by rogeriodec** [pygame/pygameweb#54]
All "**Search examples for ...**" buttons are failing because they are calling **nullege.com** using **https**, which generates the **ERR_CONNECTION_REFUSED** error.
You have to switch to just "**http**".

**Comment by illume** [comment]
Thanks for the report!

I changed it to search github for now. Which has quite a few results on there these days, and also gives better results.

**Comment by rogeriodec** [comment]
Perfect! Thank you!

**Comment by illume** [comment]
Hi @lukevp 

Thanks for pointing the issue into the right place and for following up :)

I did some comparisons of several searches, and found github seemed to return more relevant results. Also nulledge seemed to have more advertising and no https at https://www.nullege.com.

Happy to look at this again in the future, but for now github search seems better for finding examples of using pygame.

cheers, and thanks!
