### ISSUE TITLE
Feature request: RSS feeds for the news and recent releases

### ISSUE THREAD

**Issue by felixplesoianu** [pygame/pygameweb#6]
The title says it all. Newsfeeds would make it so much easier to follow what is going on in the world of Pygame. Thank you.

**Comment by illume** [comment]
There are the old feed URLs still... but we don't link to them anywhere anymore. Oops.

- http://www.pygame.org/feed/releases.php?format=RSS2.0
- http://www.pygame.org/feed/news.php?format=RSS2.0
