### ISSUE TITLE
Feature Request: Flagging Like/Content/Spam/Down

### ISSUE THREAD

**Issue by poikilos** [pygame/pygameweb#60]
There are several spam projects and dead projects. The Pygame website would be safer if there was some kind of flagging system--if it is user-maintained, maybe add to a counter and possibly even wait for admin approval, or even just a certain threshold of points to reduce administration. There could at least be some type of warning on the project page (or even on down-ranking in tag searches) for projects that are:
* spam
  * <https://www.pygame.org/project/3611>
  * (probably android virus) <https://www.pygame.org/project/3615a>
* has copyright-infringing content
  * <https://www.pygame.org/project/3620>
* site down (including links to parked sites, which can sometimes have malware)  -- maybe the user didn't realize the consequences in putting a fake website or didn't know it was a parked site (which is probably the case below), in which case just put a warning by the link or remove the link, but don't downrank the project unless there is no other link--on the project below, there is actually a working download link to mega.nz though the "website" link is a parked site (DON'T CLICK that):
  * <https://www.pygame.org/project/3623> (maybe make the default for the Website field <http://www.example.com> to prevent people from putting in fake sites intentionally when they don't have a website like in this case)

Things to Consider:
* Potentially, a per-category point system could also be used to rate projects (perhaps even just a simple thumbs up and like count).
* This way, users can help monitor pygame.org user-submitted content, before someone gets a virus or there is a DMCA takedown notice (though Nintendo doesn't seem to do much about various Mario Bros NES clones around the web, there may be other clone games I didn't see which also use ripped graphics or music).
* This system of course would have to prevent multiple points per-category by same IP address (or other uniquely identifying information) in which case your privacy policy would have to reflect that
(also, I don't see any indication the pygame organization or the website is outside of the U.S., but if so, meanwhile you could also become GDPR-compliant if the pygame uses an EU web host). Another option, though low-security, would be only store the IP of voters in RAM somehow (such as REDIS with [non-persistence](https://stackoverflow.com/questions/28785383/how-to-disable-persistence-with-redis)), so when server is restarted person could vote again, but no uniquely identifying information is permanently stored.

**Comment by illume** [comment]
Are you volunteering? There's an existing issue already open for this.

**Comment by poikilos** [comment]
I didn't find that in my search. I'm not very familiar with the python libraries the website uses but I'll take a look.

**Comment by poikilos** [comment]
@illume Hello, I was going to try to volunteer but got stuck here: https://github.com/pygame/pygameweb/issues/62
