### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by twistios** [pygame/pygameweb#91]
We I try to open the website, there is only "Seems the website is sleeping. Be right back." written and some Icons are displayed.

Known Facts (from Source Code):
Bad gateway
The web server reported a bad gateway error.
Error reference number: 502

According to [this](https://www.reddit.com/r/pygame/comments/fntz2g/pygameorg_down/) it is down since two days now.

**Comment by nift4** [comment]
Still down :(

**Comment by nift4** [comment]
That's now 2 weeks

**Comment by dan070** [comment]
Hm, still down. I'd like to access some of the docs on it. Is there any other way, or some mirror somewhere?

**Comment by nift4** [comment]
https://www.reddit.com/r/pygame/comments/fv46b9/comment/fmgty54

**Comment by nift4** [comment]
There is an mirror

**Comment by nift4** [comment]
There is an mirror

**Comment by 1stDimension** [comment]
Had the same problem. I've found this website https://devdocs.io/pygame/.

**Comment by nift4** [comment]
Please close this issue, the website is back up!
